"""
Django settings for nucleus project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import environ
env = environ.Env()
environ.Env.read_env()  # Reads the .env file

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = env.bool('DEBUG',default=False)
ALLOWED_HOSTS = ["127.0.0.1", ".vercel.app", ".now.sh"]



# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
THIRD_PARTY_APPS = [
    'phonenumber_field',
]
OUR_APPS = [
    'Accounts',
    'MCQS',
    'performance',
    'TUTORMODE',
]
INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + OUR_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nucleus.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nucleus.wsgi.application'
AUTH_USER_MODEL = 'Accounts.Account'
import os
import environ



# Get the environment
DJANGO_ENV = env('DJANGO_ENV', default='local').strip()
# Common settings
SUPABASE_URL = os.environ.get('SUPABASE_URL')
SUPABASE_ANON_KEY = os.environ.get('SUPABASE_ANON_KEY')

# Database settings
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("SUPBASE_DB_NAME"),
        "USER": env("SUPBASE_DB_USER"),
        "PASSWORD": env("SUPBASE_DB_PASSWORD"),
        "HOST": env("SUPBASE_DB_HOST"),
        "PORT": env("SUPBASE_DB_PORT"),
    }
}

# Additional settings can be customized based on DJANGO_ENV if needed
if DJANGO_ENV == 'local':
    # Local development-specific settings
    DEBUG = True
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']
    
elif DJANGO_ENV == 'production':
    # Production-specific settings
    DEBUG = False
    ALLOWED_HOSTS = [".vercel.app"]
    
else:
    raise ValueError(f"Unknown DJANGO_ENV: {DJANGO_ENV}")


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# # Initialize environment variables
# env = environ.Env()
# environ.Env.read_env()  # Reads the .env file

# # Get the environment
# DJANGO_ENV = os.environ.get('DJANGO_ENV', default='local')

# # Common settings
# SUPABASE_URL = os.environ.get('SUPABASE_URL')
# SUPABASE_ANON_KEY = os.environ.get('SUPABASE_ANON_KEY')

# if DJANGO_ENV == 'local':
#     # Local development settings
#     DATABASES = {
#         "default": {
#             "ENGINE": "django.db.backends.postgresql",
#             "NAME": os.environ.get("LOCAL_DB_NAME"),
#             "USER": os.environ.get("LOCAL_DB_USER"),
#             "PASSWORD": os.environ.get("LOCAL_DB_PASSWORD"),
#             "HOST": os.environ.get("LOCAL_DB_HOST"),
#             "PORT": os.environ.get("LOCAL_DB_PORT"),
#         }
#     }
    
# elif DJANGO_ENV == 'production':
#     # Production settings
#     DATABASES = {
#         "default": {
#             "ENGINE": "django.db.backends.postgresql",
#             "NAME": os.environ.get("SUPBASE_DB_NAME"),
#             "USER": os.environ.get("SUPBASE_DB_USER"),
#             "PASSWORD": os.environ.get("SUPBASE_DB_PASSWORD"),
#             "HOST": os.environ.get("SUPBASE_DB_HOST"),
#             "PORT": os.environ.get("SUPBASE_DB_PORT"),
#         }
#     }
    
# else:
#      raise ValueError(f"Unknown DJANGO_ENV: {DJANGO_ENV}")

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/


# Static files settings
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "public/static"),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.ERROR: "danger",
}

EMAIL_BACKEND = "backends.custom_email_backend.CustomEmailBackend"
# Email settings
EMAIL_HOST = env('EMAIL_HOST')
EMAIL_PORT = env.int('EMAIL_PORT')
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL')


# Sessions will expire after 2 weeks by default
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds

